AppNexus: Render Ads Above the Fold
protonate/amphtml pull request #1
Opened 2018-02-09 07:03 UTC by protonate

render ads that are available but not rendered when the slot is abov the fold and then scrolled into view

2018-02-09 18:29 UTC, mkendall07 requested changes

2018-02-09 18:29 UTC, mkendall07 commented on ads/appnexus.js
> +          const adObj = response && apntag.getAdForAMP(response);
is `getAdForAMP` a new function?

2018-02-09 18:29 UTC, mkendall07 commented on ads/appnexus.js
> +  const tagsRequested = apntag.requests && apntag.requests.tags;
eventually `apntag.requests.tags` will go away, is there a way to make this a more generic public API?

2018-02-09 18:45 UTC, protonate commented on ads/appnexus.js
> +          const adObj = response && apntag.getAdForAMP(response);
yep

2018-02-26 17:01 UTC, mkendall07 commented on ads/appnexus.js
> +function isAdAvailable(adObj) {
shouldn't this be `adIsAvailable`?

2018-02-26 17:09 UTC, protonate commented on ads/appnexus.js
> +function isAdAvailable(adObj) {
this is consistent with conventions

2018-02-26 17:09 UTC, merged